### PR TITLE
Increase time granularity

### PR DESCRIPTION
**Pull request by FISHMANPET**
Increase granularity of timing info sent to Splunk

### CODE REVIEW

**Comment by travis-sobeck** [comment]
Looks good, noticed the psd1 fine "binary" .. do you want to add the file to git that resolves that?

**Comment by FISHMANPET** [comment]
Turns out that trick doesn't work,  it's... complicated.  Someday I'll figure out how to do it reliably, last time I messed around I accidentally broke another module, so we'll just leave it alone for now.

**Comment by FISHMANPET** [comment]
Actually the problem was when i added the file AND changed the encoding, just changing the encoding should be fine, so I just pushed that

**Comment by travis-sobeck** [comment]
Considering just how many scripts rely on this, I'll merge monday morning :)

**Comment by travis-sobeck** [comment]
@FISHMANPET I ran a couple test runbooks from the mpt runbooks servers, looks good.

**Pull request merged**
